language: rust
rust: nightly
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libXxf86vm-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi

os:
  - linux
  - osx

script:
  - cargo build --verbose
  - cargo build --features texture_surface --verbose
  # FIXME(ecoal95): Travis' ubuntu doesn't have the neccessary graphics stack and it fails
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then cargo test --verbose; fi
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then cargo test --features texture_surface --verbose; fi
