[package]
name = "offscreen_gl_context"
version = "0.0.1"
authors = ["ecoal95 <ecoal95@gmail.com>"]

[features]
texture_surface = ["layers"]

[dependencies]
libc = "*"
log  = "*"
gleam = "0.1"

[dependencies.geom]
git = "https://github.com/servo/rust-geom"

[dependencies.layers]
git = "https://github.com/servo/rust-layers"
optional = true

[target.x86_64-apple-darwin.dependencies]
core-foundation = "*"
cgl = "0.1"

[target.i686-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.x86_64-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.arm-unknown-linux-gnueabihf.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "*"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "*"
features = ["xlib"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "*"
features = ["xlib"]

[target.arm-linux-androideabi.dependencies.egl]
git = "https://github.com/servo/rust-egl"
