[package]
name = "offscreen_gl_context"
license = "MIT / Apache-2.0"
version = "0.1.0"
authors = ["ecoal95 <ecoal95@gmail.com>", "The Servo Project Developers"]
description = "Creation and manipulation of HW accelerated offscreen rendering contexts in multiple platforms. Originally intended for the Servo project WebGL implementation."
repository = "https://github.com/ecoal95/rust-offscreen-rendering-context"
build = "build.rs"

[build-dependencies]
gl_generator = "0.4"
khronos_api = "1.0"

[dependencies]
log  = "0.3.3"
gleam = "0.1"
euclid = "0.4"
serde = "0.6.1"
serde_macros = "0.6.1"

[target.x86_64-apple-darwin.dependencies]
core-foundation = "0.2.0"
cgl = "0.1"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "2.3.0"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "2.3.0"
features = ["xlib"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "2.3.0"
features = ["xlib"]

[target.aarch64-unknown-linux-gnu.dependencies.x11]
version = "2.3.0"
features = ["xlib"]

[target.x86_64-pc-windows-gnu.dependencies]
servo-glutin = "0.4"
